coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts" 
  - "**/tests/**"
  - "src/tests/**"
  - "**/*.d.ts"
  - "coverage/**"
  - "node_modules/**"
  - ".github/**"
  - "*.config.*"
  - "drizzle.config.ts"
  - "worker-configuration.d.ts"

flags:
  unit:
    paths:
      - src/
    carryforward: true